# This is a basic workflow to help you get started with Actions

name: compile-run

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Pull choosenim
        run: curl https://nim-lang.org/choosenim/init.sh -sSf > install-nim.sh
        
        
      - name: Install nim
        run: chmod +x install-nim.sh && ./install-nim.sh -y
        
      # Runs a single command using the runners shell
      - name: Run tests on 1.2
        run: export PATH=/home/runner/.nimble/bin:$PATH && choosenim 1.2.0 && nimble refresh && nimble install sequtils2 && nim c -r --threads:on tests/test*
        
      - name: Run tests on 1.4
        run: export PATH=/home/runner/.nimble/bin:$PATH && choosenim 1.4.0 && nimble refresh && nimble install sequtils2 && nim c -r --threads:on tests/test*

